config/routes.rb
Rails.application.routes.draw do


  mount Forem::Engine, :at => '/forums'

  devise_for :users

  resources :sheets

  root to: 'pages#home'

end

app/models/sheet.rb
class Sheet < ActiveRecord::Base

include ActiveModel::Conversion
extend  ActiveModel::Naming

    belongs_to :user
	belongs_to :topic
#Moerthods allow for the interpretation of roll modifier for inclusion in the roll_die method within post_controller_decorator.
	def str_mod
		(str-10)/2
	end

	def dex_mod
		(dex-10)/2
	end

	def con_mod
		(con-10)/2
	end

	def int_mod
		(int-10)/2
	end

	def wis_mod
		(wis-10)/2
	end

	def cha_mod
		(cha-10)/2
	end

	def armor_class
		armor_bonus + shield_bonus + dex_mod + nat_armor + 10
	end

	def touch_ac
		shield_bonus + dex_mod + 10
	end

	def flat_foot
		armor_bonus + shield_bonus + nat_armor + 10
	end

	def fort
		fort_save + con_mod
	end

	def will
		will_save + wis_mod
	end

	def ref
		ref_save + dex_mod
	end

	def cmb
		base_attack_bonus + str_mod
	end

	def cmd
		base_attack_bonus + str_mod + dex_mod + 10
	end

	def size_word
		if character_size == 1
			"Large"
		elsif character_size == 0
			"Medium"
		elsif character_size == -1
			"Small"
		end
	end

	def attack_mod
		base_attack_bonus + str_mod
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :sheets
  

  def forem_name
    #screen_name needs to be re-introduced, removed during the formatting of the user registration page.
  	screen_name
  end

  def forem_email
  	email
  end       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def forem_user
    current_user
  end
  helper_method :forem_user

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
		@p = Forem::Post.new
	end
end

app/controllers/sheets_controller.rb
class SheetsController < ApplicationController
  before_filter :find_topic, :only => [:new]

  def new
      @sheet = @topic.sheets.build
      #As sheets are outside of the Forem engine, the forum_id does not pass through as a resource.
      @sheet.forum_id = @topic.forum.id
  end

  def create

      @sheet = Sheet.new(sheet_params)
      #As sheets are outside of the Forem engine, the user does not pass through as a resource.
      @sheet.user = forem_user

      if @sheet.save
        create_successful
      else
        create_failed
      end
  end

  def edit
    #Allows for params embedded in the URL to be used to trace the sheet matching the oriignating topic and user.
    @sheet = Sheet.where(topic_id: params[:topic_id], user_id: forem_user.id).first
    #Likely overkill, may be worth removing during refactoring.
    @sheet.forum_id = params[:forum_id]
  end

  def update
      #Allows for params embedded in the URL to be used to trace the sheet matching the oriignating topic and user.
      @sheet = Sheet.where(topic_id: params[:sheet][:topic_id], user_id: forem_user.id).first
      @sheet.update_attributes(sheet_params)
      #As there is no association between the sheet and the topic or user, these values are passed on through the URL to allow for the user to re-enter the engine
      redirect_to forem.forum_topic_url(:action => "show", :contorller => "forem/topics", :format => nil, :forum_id => @sheet.forum_id, :id => @sheet.topic_id)
  end

  def destroy
  end

  def show
  end

      private

    def sheet_params
      params.require(:sheet).permit(:forum_id, :topic_id, :character_name, :str, :dex, :con, :wis, :int, :cha, :character_race, :character_class, :character_alignment, :armor_bonus, :shield_bonus, :fort_save, :ref_save, :will_save, :base_attack_bonus, :character_size, :nat_armor)
    end

    def find_topic
      @topic = Forem::Topic.find(params[:topic_id])
    end

    def create_successful
      flash[:notice] = "Your character sheet has been successfully saved."
      #As there is no association between the sheet and the topic or user, these values are passed on through the URL to allow for the user to re-enter the engine
      redirect_to forem.forum_topic_url(:action => "show", :contorller => "forem/topics", :format => nil, :forum_id => @sheet.forum_id, :id => @sheet.topic_id)
    end

    def create_failed
      params[:reply_to_id] = params[:post][:reply_to_id]
      flash.now.alert = "Your character sheet has not been successfully saved.  Please re-submit."
      render :action => "new"
    end

    def update_successful
      #As there is no association between the sheet and the topic or user, these values are passed on through the URL to allow for the user to re-enter the engine
      redirect_to forem.forum_topic_url(:action => "show", :contorller => "forem/topics", :format => nil, :forum_id => @sheet.forum_id, :id => @sheet.topic_id)
    end

    def update_failed
      flash.now.alert = t("forem.post.not_edited")
      render :action => "edit"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sheets_helper.rb
module SheetsHelper
end

app/views/forem/admin/categories/_form.html.erb
<%= simple_form_for [forem, :admin, @category] do |f| %>
  <%= f.input :name %>
  <%= f.submit :class => "btn btn-primary" %>
<% end %>

app/views/forem/admin/categories/edit.html.erb
<h2><%= t("forem.admin.category.edit", :title => @category.name) %></h2>

<%= render "form" %>

app/views/forem/admin/categories/index.html.erb
<h2><%= t("forem.admin.category.index") %></h2>
<%= link_to t('back_to_admin', :scope => "forem.admin"), forem.admin_root_path %><br><br>
<%= link_to t("forem.admin.category.new_link"), forem.new_admin_category_path, :class => "btn btn-primary" %><br><br>

<table id='forums' class='forums table-striped table' cellspacing='0'>
  <thead>
    <tr>
      <th><%= t('edit', :scope => 'forem.admin.categories') %></th>
      <th><%= t('delete', :scope => 'forem.admin.categories') %></th>
      <th><%= t('category', :scope => 'forem.admin.categories') %></th>

    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr class="forum <%= cycle("odd", "even") %>">
        <td><%= link_to t('edit', :scope => 'forem.admin.categories'), forem.edit_admin_category_path(category), :class => "btn btn-info" %></td>
        <td><%= link_to t('delete', :scope => 'forem.admin.categories'), forem.admin_category_path(category), :method => :delete, 
        data: { :confirm => t("delete_confirm", :scope => 'forem.admin.categories') }, :class => "btn btn-danger" %></td>
        <td>
          <%= forem_emojify(category.name) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('forem.admin.forum.index'), forem.admin_forums_path %>

app/views/forem/admin/categories/new.html.erb
<h2><%= t('new', :scope => 'forem.admin.category') %></h2>

<%= render "form" %>

app/views/forem/admin/forums/_form.html.erb
<%= simple_form_for [forem, :admin, @forum] do |f| %>
  <%= f.association :category, :include_blank => false %><br/>
  <%= f.input :title %><br/>
  <%= f.input :description, :as => :text %>

  <h3><%= t('forem.admin.forum.moderator_groups') %></h3>
  <%= f.association :moderators, :as => :check_boxes %>
  <%= f.submit :class => "btn btn-primary" %>
<% end %>

app/views/forem/admin/forums/edit.html.erb
  <h2><%= t("forem.forum.edit", :title => forem_emojify(@forum.title)).html_safe %></h2>

  <%= render "form" %>

app/views/forem/admin/forums/index.html.erb
<div>
  <h2><%= t("forem.admin.forum.index") %></h2>
  <%= link_to t('back_to_admin', :scope => "forem.admin"), forem.admin_root_path %><br><br>
  <%= link_to t("forem.admin.forum.new_link"), forem.new_admin_forum_path, :class => "btn btn-primary" %>

  <% @forums.group_by(&:category).each do |category, forums| %>
    <h2><%= category.try(:name) || t('.no_category') %></h2>

    <table id='forums' class='forums table table-striped' cellspacing='0'>
      <thead>
        <tr>
          <th><%= t('edit', :scope => 'forem.admin.forums') %></th>
          <th><%= t('delete', :scope => 'forem.admin.forums') %></th>
          <th><%= t('forum', :scope => 'forem.general') %></th>
          <th><%= t('topics', :scope => 'forem.general') %></th>
          <th><%= t('posts', :scope => 'forem.general') %></th>
        </tr>
      </thead>
      <tbody>
        <% forums.each do |forum| %>
          <tr class="forum <%= cycle("odd", "even") %>">
            <td><%= link_to t('edit', :scope => 'forem.admin.forums'), forem.edit_admin_forum_path(forum), :class => "btn btn-info" %></td>
            <td><%= link_to t('delete', :scope => 'forem.admin.forums'), forem.admin_forum_path(forum), :method => :delete, data: { :confirm => t("delete_confirm", :scope => 'forem.admin.forums') }, :class => "btn btn-danger" %></td>
            <td>
              <%= link_to forem_emojify(forum.title), forem.forum_path(forum) %>
              <div class='description'><%= forem_format(forum.description) %></div>
              <%= t('.last_post') %>
              <% if last_post = forum.posts.last %>
  <%= link_to(forem_emojify(last_post.topic.subject), forem.forum_topic_path(forum, last_post.topic)) -%> <%= t('by') %> <%= last_post.user.screen_name %> <%= time_ago_in_words(last_post.created_at) -%>
              <% else %>
                <%= t('.none') %>
              <% end %>
              <br>
              <span class='moderators'>
                <strong><%= t('.moderators') %>:</strong>
                <% if forum.moderators.exists? %>
                  <% forum.moderators.map do |moderator| %>
                    <%= link_to moderator, [forem, :admin, moderator] %>
                  <% end.to_sentence %>
                <% else %>
                  <%= t('.none') %>
                <% end %>
              </span>
            </td>
            <td><%= forum.topics.count %></td>
            <td><%= forum.posts.count %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/forem/admin/forums/new.html.erb
<h2><%= t("forem.forum.new") %></h2>

<%= render "form" %>

app/views/forem/admin/topics/_form.html.erb
<%= simple_form_for [forem, :admin, @topic.forum, @topic] do |f| %>
  <%= f.input :subject %>
  <%= f.association :forum , :label => "Forum" %>
  <%= f.label :locked %>
  <%= f.check_box :locked %>
  <%= f.label :pinned %>
  <%= f.check_box :pinned %>
  <%= f.label :hidden %>
  <%= f.check_box :hidden %>

  <br />
  <%= f.submit :class => "btn btn-primary" %>
<% end %>

app/views/forem/admin/topics/edit.html.erb
<h2><%= t("forem.topic.edit", :subject => @topic.subject) %></h2>

<%= render "form" %>

app/views/forem/categories/_category.html.erb
<% if can?(:read, category) %>
  <div id='category_<%= category.id %>' class='category'>
    <h2><%= link_to forem_emojify(category.name), [forem, category] %></h2>
    <%= render "/forem/forums/listing", :category => category %>
  </div>
<% end %>

app/views/forem/categories/show.html.erb
<div class='category'>
  <h2><%= link_to 'Versions', forem.forums_path %> &raquo; <%= link_to 'Version One', [forem, @category] %></h2>
  <%= render @category %>
</div>

app/views/forem/forums/_forum.html.erb
<% if can?(:read, forum) %>
  <tr class="forum <%= cycle("odd", "even") %>">
    <td>
      <%= link_to forem_emojify(forum.title), forem.forum_path(forum), :class => "title" %>
      <div class='description'><%= forem_format(forum.description) %></div>
      <%= t('forem.forums.index.last_post') -%>
      <span class='last_post'>
        <% if last_post = forum.last_post_for(forem_user) -%>
          <%= link_to(forem_emojify(last_post.topic.subject), forem.forum_topic_path(forum, last_post.topic)) -%> <%= t('by') %> <%= last_post.user.forem_name %>
          <time datetime="<%= last_post.created_at.to_s(:db) -%>"><%= "#{time_ago_in_words(last_post.created_at)} #{t("ago")}" %></time>
        <% else %>
          <%= t('forem.forums.index.none') -%>
        <% end %>
      </span>
    </td>
    <td class="topics-count"><%= topics_count(forum) %></td>
    <td class="posts-count"><%= posts_count(forum) %></td>
    <td class="views-count"><%= forum.views_count %></td>
  </tr>
<% end %>

app/views/forem/forums/_head.html.erb
<div id='forum'>
<!--   Slight changes made to the naming convention, which no longer receives language conditioning.
 -->  
<!-- Forums changed to Versions, however version titles are not used as only D and D version 1 is supported. Same with the reference to Version One Games.
 -->
 <h2><%= link_to 'Versions', forem.root_path %> &raquo; <%= link_to 'Version One', [forem, forum.category] %> &raquo; <%= link_to 'Active Games', [forem, forum] %></h2>
  <span id='description'><%= forem_format(forum.description) %></span>
  <div id='forum_topic_links' class='btn-group'>
    <% unless @topic.try(:new_record?) %>
      <% if can? :create_topic, @forum %>
        <%= link_to t('forem.topic.links.new'), forem.new_forum_topic_path(forum), :class => "btn btn-primary", :id => "new-topic" %>
      <% end %>
    <% end %>
    <% if @topic %>
      <%= link_to t('forem.topic.links.back_to_topics'), forem.forum_path(forum), :class => "btn" %>
    <% end %>
    <% if can? :moderate, @forum %>
      <%= link_to t('forem.forum.moderator_tools'), forem.forum_moderator_tools_path(forum), :class => "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/forem/forums/_listing.html.erb
<table id='forums' class='forums table table-striped' cellspacing='0'>
  <thead>
  <tr>
    <th class="desc-and-last-post">Version</th>
    <th class="topics-count"><%= t('topics', :scope => 'forem.general') %></th>
    <th class="posts-count"><%= t('posts', :scope => 'forem.general') %></th>
    <th class="views-count"><%= t('forem.forums.index.views') %></th>
  </tr>
  </thead>
  <tbody>
    <%= render category.forums %>
  </tbody>
</table>

app/views/forem/forums/index.html.erb
<div id='forums_container'>
<!-- 	Title overwritten temporarily, to be amended once multiple versions are supported.
 -->	
  <h1 id='forums_title'>Versions</h1>

  <%= render @categories %>
</div>

<br>
<footer id='admin_link'>
<!-- Link back to Admin controls commented out as it is not required for our business case.
 -->
  <!--<% if forem_admin? %>
    <%= link_to t("area", :scope => "forem.admin"), forem.admin_root_path %>
  <% end %> -->
</footer>

app/views/forem/forums/show.html.erb
<div class='forum'>
  <%= render :partial => 'forem/forums/head', :locals => { :forum => @forum } %>

  <%= forem_pages_widget(@topics) %>
  <table class='topics table-striped table' cellspacing='0'>
    <thead>
      <tr>
        <th class="icon"></th>
        <th class="byline">Game</th>
        <th class="latest-post text-center"><%= t('forem.topic.headings.latest') -%></th>
        <th class="posts-count text-center"><%= t('forem.topic.headings.posts') -%></th>
        <th class="views-count text-center"><%= t('forem.topic.headings.views') -%></th>
      </tr>
    </thead>
    <tbody>
      <% if @topics.empty? %>
        <tr><td colspan='5' align='center'><%= t('forem.topic.none') %></td></tr>
      <% end %>
      <%= render @topics %>
    </tbody>
  </table>
  <%= forem_pages_widget(@topics) %>
</div>

app/views/forem/moderation/_options.html.erb
<p>
  <%= f.radio_button "moderation_option", "approve" %>
  <%= f.label "moderation_option_approve", t('approve', :scope => 'forem.posts.moderation'), :class => "label label-success" %>
</p>
<p>
  <%= f.radio_button "moderation_option", "spam" %>
  <%= f.label "moderation_option_spam", t('spam', :scope => 'forem.posts.moderation'), :class => "label label-danger" %>
</p>
<br>
<%= f.submit t('moderate', :scope => 'forem.posts.moderation'), :class => "btn btn-primary" %>

app/views/forem/moderation/index.html.erb
<h2><%= t('.title', :forum => forum) %></h2>

<h3><%= t('posts_count', :count => @posts.count, :scope => 'forem.general') %></h3>

<%= form_tag forem.forum_moderate_posts_url(forum), :method => :put do %>
  <div id='posts'>
    <% @posts.limit(25).group_by(&:topic).each do |topic, posts| %>
      <h4><%= forem_emojify(topic.forum.title) %> &raquo; <%= forem_emojify(topic.subject) %></h4>
      <%= render posts, :mass_moderation => true %>
    <% end %>
  </div>
<% end %>

<h3><%= t('topics_count', :count => @topics.count, :scope => 'forem.forum') %></h3>

<div id='topics'>
  <% @topics.limit(25).each_with_index do |topic, topic_counter| %>
    <div id='topic_<%= topic_counter + 1 %>' class='topic <%= cycle('odd', 'even', name: 'topics') -%>'>
      <div class='moderation alert'>
        <%= link_to forem_emojify(topic.subject),
                    forem.forum_topic_path(forum, topic) %>
      </div>
    </div>
  <% end %>
</div>

app/views/forem/posts/_form.html.erb
<%= f.input :text, :input_html => { :class => "field col-md-12" } %><br>
<div class="roll_box">Number of Dice <%= f.text_field "no_of_die" %></div>
<div class="roll_box">Number of Sides <%= f.text_field "no_of_side" %></div>
<div class="roll_box">Modifier <%= f.select :roll_mod, options_for_select([["Strength Mod", "str_mod"], ["Dexterity Mod", "dex_mod"],["Constitution Mod", "con_mod"], ["Wisdom Mod", "wis_mod"], ["Intelegence Mod", "int_mod"], ["Chrisma Mod", "cha_mod"], ["Attack mod", "attack"], ["Fortitude Save", "fort_save"], ["Will Save", "will_save"], ["Reflex Save", "ref_save"], ["Combat Maneuver Bonus", "cmb"]]) %></div>

<% if params[:reply_to_id] %>
  <%= f.hidden_field :reply_to_id, :value => params[:reply_to_id] %>
<% end %>

app/views/forem/posts/_moderation_tools.html.erb
<%= fields_for "posts[#{post.id}]" do |f| %>
  <%= render "/forem/moderation/options", :f => f %>
<% end %>
<br>

app/views/forem/posts/_post.html.erb
<a name='post-<%= post.id %>'></a>
<div class="row">
  <div id='post_<%= post_counter + 1 %>' class='post <%= cycle('odd', 'even') -%> col-md-12'>
    <% if post.pending_review? %>
      <div class='moderation alert'>
        <%= t(".pending_review") %>
        <% if forem_admin_or_moderator?(post.topic.forum) %>
          <% if local_assigns[:mass_moderation] %>
            <%= render "/forem/posts/moderation_tools", :post => post %>
          <% else %>
            <%= form_tag forem.forum_moderate_posts_path(post.topic.forum), :method => :put do %>
              <%= render "/forem/posts/moderation_tools", :post => post %>
            <% end %>
          <% end %>
        <% end %>
      </div><!-- for moderation alert -->
    <% end %>

    <div class='contents'>
      <div class='user col-md-2'>
        <div class='username'>
          <% if post.user.is_a?(Forem::NilUser) %>
            <%= t(:deleted) %>
          <% else %>
            <%= link_to_if Forem.user_profile_links, post.user.forem_name, [main_app, post.user] %>
          <% end %>
        </div><!-- for username -->
        <!-- Gravitar function not working within engine, overridden with gravatar_image_tag gem. -->
        <div class='icon'><%= gravatar_image_tag post.user.email %></div>
      </div><!-- for user col-md-2 -->

      <div class='contents col-md-7'>
        <a href='#post-<%= post.id %>'>
          <%= post_time_tag(post) %>
        </a>
        <!-- where dice roll is displayed -->
        <div class="post_text">
        <%= forem_format(post.text) %>
        </div><!-- for post_text -->
        


<!--         <p> Rolled: d +  = </p>
 -->
        <!-- how to get user id -->
        <!-- <p> My user id is <%= forem_user.id %> </p> -->
        <!-- finding topic id -->
        <!-- <p> The topic id is <%= post.topic.id %> </p> -->

        <% if post.reply_to %>
          <div class='in-reply-to'>
            <%= link_to "#{t("forem.post.in_reply_to")} #{post.reply_to.user.forem_name}", "#post-#{post.reply_to.id}" %>
          </div><!-- for in-reply-to -->
        <% end %>        
      </div><!-- for contents col-md-7 -->
<!-- Table allows for the display of the player's roll selection for a given turn and the resulting output of that roll -->
    <div class="roll_table">
      <table>
        <td class="roll_masthead" colspan="2">Roll Details and Results</td>
      </tr>
            <!-- Breaks added as forem_format method forces a line break, allows for content to align properly and remain visually appealing. -->
        <td class="roll_title">Number of Dice:<br></td>
        <td class="roll_result"><%= forem_format(post.no_of_die.to_s) %></td>
      </tr>
      <tr>
        <td class="roll_title">Number of Sides:<br></td>
       <td class="roll_result"><%= forem_format(post.no_of_side.to_s) %></td>
     </tr>
     <tr>
        <td class="roll_title">Roll Modifier:<br></td>
        <td class="roll_result"><%= forem_format(post.roll_mod.to_s) %></td>
     </tr>
     <tr>
        <td class="roll_title">Result:<br></td>
        <td class="roll_result"><%= forem_format(post.result.to_s) %></td>
      </tr>
    </table>
    </div><!-- for roll_table -->
    </div><!-- for contents -->
    <% if forem_user %>
          <div class="pst_btn_group btn-group">
            <% if can?(:reply, post.topic) %>
              <% if post.topic.can_be_replied_to? %>
                <%= link_to t('reply', :scope => 'forem.topic'), forem.new_forum_topic_post_path(post.forum, post.topic, :reply_to_id => post.id), :class => "btn btn-primary" %>
                <%= link_to t('quote', :scope => 'forem.topic'), forem.new_forum_topic_post_path(post.forum, post.topic, :reply_to_id => post.id, :quote => true), :class => "btn btn-success" %>
              <% end %>
            <% end %>
            <% if post.owner_or_admin?(forem_user) %>
              <% if can?(:edit_post, post.topic.forum) %>
                <%= link_to t('edit', :scope => 'forem.post'), forem.edit_forum_topic_post_path(post.forum, post.topic, post), :class => "btn btn-info" %>
              <% end %>
              <% if can?(:destroy_post, post.topic.forum) %>
                <%= link_to t('delete', :scope => 'forem.topic'), forem.forum_topic_post_path(post.forum, post.topic, post), :method => :delete, data: { :confirm => t("are_you_sure") }, :class => "btn btn-danger" %>
              <% end %>
            <% end %>
          </div><!-- pst_btn_group btn-group -->
        <% end %>
  </div><!-- for post <%= cycle('odd', 'even') -%> col-md-12 -->

</div><!-- for row -->
<br>

app/views/forem/posts/_reply_to_post.html.erb
<a name='post-<%= post.id %>'></a>
<div id='post_<%= post.id %>' class='reply_to_post post <%= cycle('odd', 'even') -%> col-md-10'>
  <div class='user col-md-2'>
    <div class='username'>
      <%= link_to_if Forem.user_profile_links, post.user.forem_name, [main_app, post.user] %>
    </div>
    <div class='icon'><%= gravatar_image_tag post.user.email %></div>
  </div>

  <div class='contents col-md-7'>
    <time datetime="<%= post.created_at.to_s(:db) -%>"><%= "#{time_ago_in_words(post.created_at)} #{t("ago")}" %></time>
    <%= forem_format(post.text) %>

    <% if post.reply_to %>
      <span class='in_reply_to'>
        <%= link_to "#{t("forem.post.in_reply_to")} #{post.reply_to.user.forem_name}", "#post-#{post.reply_to.id}" %>
      </span>
    <% end %>
  </div>
</div>

app/views/forem/posts/edit.html.erb
<%= render :partial => 'forem/forums/head', :locals => { :forum => @topic.forum } %>

<h2><%= t("forem.post.edit", :post => @post) %></h2>

<%= simple_form_for [forem, @topic.forum, @topic, @post] do |f| %>
  <%= render :partial => "form", :locals => { :f => f } %>
  <%= f.submit t("forem.post.buttons.edit"), :class => "btn btn-primary" %>
<% end %>

app/views/forem/topics/_head.html.erb
<h2><%= link_to 'Versions', forem.forums_path %> &raquo; <%= link_to 'Version One', [forem, topic.forum] %> &raquo; <%= forem_emojify(topic.subject) %></h2>

app/views/sheets/show.html.erb
<%= link_to "My Characters", "/sheets" %> | <%= link_to "Edit", edit_sheet_path(@sheets[:id]) %> | <%= link_to "Delete", @sheet, :confirm => "Are you sure you want to delete this character?", :method => :delete %>
<h1><%= @sheets.character_name %></h1>
<p>Race: <%= @sheets.character_race %> Class: <%= @sheets.character_class %> Alignment: <%= @sheets.character_alignment %> Size: <%= @sheets.size_word %></p>

<!-- Base Abilities -->
<p>Strength: <%= @sheets.str %> Str mod: <%= @sheets.str_mod %> </p>
<p>Dexterity: <%= @sheets.dex %> Dex mod: <%= @sheets.dex_mod %> </p>
<p>Constitution: <%= @sheets.con %> Con mod: <%= @sheets.con_mod %> </p>
<p>Wisdom: <%= @sheets.wis %> Wis mod: <%= @sheets.wis_mod %> </p>
<p>Intelegence: <%= @sheets.int %> Int mod: <%= @sheets.int_mod %> </p>
<p>Chrisma: <%= @sheets.cha %> Cha mod: <%= @sheets.cha_mod %> </p>

<!-- AC -->
<p>Armor Class: <%= @sheets.armor_class %> = Armor: <%= @sheets.armor_bonus %> + Shield: <%= @sheets.shield_bonus %> + Dex mod: <%= @sheets.dex_mod %> + 10 </p>
<p>Touch AC: <%= @sheets.shield_bonus + @sheets.dex_mod + 10 %></p>
<p>Flat-Footed: <%= @sheets.armor_bonus + @sheets.shield_bonus + 10 %></p>

<!-- Saving Throws -->
<p>Fortitude Save: <%= @sheets.fort %> = Base: <%= @sheets.fort_save %> + Con Mod: <%= @sheets.con_mod %>
<p>Reflex Save: <%= @sheets.ref %> = Base: <%= @sheets.ref_save %> + Dex Mod: <%= @sheets.dex_mod %>
<p>Will Save: <%= @sheets.will %> = Base: <%= @sheets.will_save %> + Wis Mod: <%= @sheets.wis_mod %>

<!-- Attack! -->
<p>Base Attack Bonus: <%= @sheets.base_attack_bonus %></p>
<p>CMB: <%= @sheets.cmb %> = base_attack_bonus: <%= @sheets.base_attack_bonus %> + Str mod: <%= @sheets.str_mod %> </p>
<p>CMD: <%= @sheets.cmd %> = base_attack_bonus: <%= @sheets.base_attack_bonus %> + Str mod: <%= @sheets.str_mod %> + Dex mod: <%= @sheets.dex_mod %> + 10 </p>